version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql:8.0
    volumes:
      - /opt/mysql_data:/var/lib/mysql
    environment:
      host: $${{MYSQL_HOST}
      port: $${MYSQL_PORT}
      user: $${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: $${MYSQL_PASS}
      database: $${MYSQL_DB}
    